name: ParallelCluster CI

on: [push, pull_request]

jobs:
  depcheck:
    runs-on: ubuntu-latest
    name: DepCheck
    steps:
      - uses: actions/checkout@v1
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          path: '.'
          format: 'HTML'
          project: 'aws-parallelcluster-node'
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        name:
          - Python 3.9 Tests
          - Python 3.10 Tests
          - Python 3.9 Tests Coverage
          - Code Checks
        include:
          - name: Python 3.9 Tests
            python: 3.9
            toxdir: cli
            toxenv: py39-nocov
          - name: Python 3.10 Tests
            python: '3.10'
            toxdir: cli
            toxenv: py310-nocov
          - name: Python 3.9 Tests Coverage
            python: 3.9
            toxdir: cli
            toxenv: py39-cov
          - name: Code Checks
            python: 3.9
            toxdir: cli
            toxenv: code-linters

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}
      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ endsWith(matrix.toxenv, '-cov') }}
        with:
          files: coverage.xml
          flags: unittests
          verbose: true
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
